// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AddFilesData, AddFilesErrors, AddFilesResponses, CreateDisplayData, CreateDisplayErrors, CreateDisplayResponses, CreatePlaylistData, CreatePlaylistErrors, CreatePlaylistResponses, CreateScheduleData, CreateScheduleErrors, CreateScheduleResponses, DeleteDisplayData, DeleteDisplayErrors, DeleteDisplayResponses, DeleteFilesData, DeleteFilesErrors, DeleteFilesResponses, DeletePlaylistData, DeletePlaylistErrors, DeletePlaylistResponses, DeleteScheduleData, DeleteScheduleErrors, DeleteScheduleResponses, GetAllPathsListData, GetAllPathsListResponses, GetAllPathsTreeData, GetAllPathsTreeResponses, ReadDisplaysData, ReadDisplaysResponses, ReadPlaylistData, ReadPlaylistResponses, ReadScheduleData, ReadScheduleResponses, ScheduleInfoData, ScheduleInfoErrors, ScheduleInfoResponses, UpdateDisplayData, UpdateDisplayErrors, UpdateDisplayResponses, UpdatePlaylistData, UpdatePlaylistErrors, UpdatePlaylistResponses, UpdateScheduleData, UpdateScheduleErrors, UpdateScheduleResponses } from './types.gen';
import { vAddFilesData, vAddFilesResponse, vCreateDisplayData, vCreateDisplayResponse, vCreatePlaylistData, vCreatePlaylistResponse, vCreateScheduleData, vCreateScheduleResponse, vDeleteDisplayData, vDeleteDisplayResponse, vDeleteFilesData, vDeleteFilesResponse, vDeletePlaylistData, vDeletePlaylistResponse, vDeleteScheduleData, vDeleteScheduleResponse, vGetAllPathsListData, vGetAllPathsListResponse, vGetAllPathsTreeData, vGetAllPathsTreeResponse, vReadDisplaysData, vReadDisplaysResponse, vReadPlaylistData, vReadPlaylistResponse, vReadScheduleData, vReadScheduleResponse, vScheduleInfoData, vScheduleInfoResponse, vUpdateDisplayData, vUpdateDisplayResponse, vUpdatePlaylistData, vUpdatePlaylistResponse, vUpdateScheduleData, vUpdateScheduleResponse } from './valibot.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const readDisplays = <ThrowOnError extends boolean = false>(options?: Options<ReadDisplaysData, ThrowOnError>) => (options?.client ?? client).get<ReadDisplaysResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vReadDisplaysData, data),
    responseValidator: async (data) => await v.parseAsync(vReadDisplaysResponse, data),
    url: '/api/display',
    ...options
});

export const createDisplay = <ThrowOnError extends boolean = false>(options: Options<CreateDisplayData, ThrowOnError>) => (options.client ?? client).post<CreateDisplayResponses, CreateDisplayErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vCreateDisplayData, data),
    responseValidator: async (data) => await v.parseAsync(vCreateDisplayResponse, data),
    url: '/api/display',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteDisplay = <ThrowOnError extends boolean = false>(options: Options<DeleteDisplayData, ThrowOnError>) => (options.client ?? client).delete<DeleteDisplayResponses, DeleteDisplayErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vDeleteDisplayData, data),
    responseValidator: async (data) => await v.parseAsync(vDeleteDisplayResponse, data),
    url: '/api/display/{uuid}',
    ...options
});

export const updateDisplay = <ThrowOnError extends boolean = false>(options: Options<UpdateDisplayData, ThrowOnError>) => (options.client ?? client).put<UpdateDisplayResponses, UpdateDisplayErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vUpdateDisplayData, data),
    responseValidator: async (data) => await v.parseAsync(vUpdateDisplayResponse, data),
    url: '/api/display/{uuid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete files and directories
 *
 * ids ending with a `'/'` will be treated as a dir, and recursively remote all contained items if present.
 */
export const deleteFiles = <ThrowOnError extends boolean = false>(options: Options<DeleteFilesData, ThrowOnError>) => (options.client ?? client).delete<DeleteFilesResponses, DeleteFilesErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vDeleteFilesData, data),
    responseValidator: async (data) => await v.parseAsync(vDeleteFilesResponse, data),
    url: '/api/files',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const addFiles = <ThrowOnError extends boolean = false>(options: Options<AddFilesData, ThrowOnError>) => (options.client ?? client).post<AddFilesResponses, AddFilesErrors, ThrowOnError>({
    ...formDataBodySerializer,
    requestValidator: async (data) => await v.parseAsync(vAddFilesData, data),
    responseValidator: async (data) => await v.parseAsync(vAddFilesResponse, data),
    url: '/api/files',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const getAllPathsList = <ThrowOnError extends boolean = false>(options?: Options<GetAllPathsListData, ThrowOnError>) => (options?.client ?? client).get<GetAllPathsListResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vGetAllPathsListData, data),
    responseValidator: async (data) => await v.parseAsync(vGetAllPathsListResponse, data),
    url: '/api/files/list',
    ...options
});

export const getAllPathsTree = <ThrowOnError extends boolean = false>(options?: Options<GetAllPathsTreeData, ThrowOnError>) => (options?.client ?? client).get<GetAllPathsTreeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vGetAllPathsTreeData, data),
    responseValidator: async (data) => await v.parseAsync(vGetAllPathsTreeResponse, data),
    url: '/api/files/tree',
    ...options
});

export const readPlaylist = <ThrowOnError extends boolean = false>(options?: Options<ReadPlaylistData, ThrowOnError>) => (options?.client ?? client).get<ReadPlaylistResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vReadPlaylistData, data),
    responseValidator: async (data) => await v.parseAsync(vReadPlaylistResponse, data),
    url: '/api/playlist',
    ...options
});

export const createPlaylist = <ThrowOnError extends boolean = false>(options: Options<CreatePlaylistData, ThrowOnError>) => (options.client ?? client).post<CreatePlaylistResponses, CreatePlaylistErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vCreatePlaylistData, data),
    responseValidator: async (data) => await v.parseAsync(vCreatePlaylistResponse, data),
    url: '/api/playlist',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deletePlaylist = <ThrowOnError extends boolean = false>(options: Options<DeletePlaylistData, ThrowOnError>) => (options.client ?? client).delete<DeletePlaylistResponses, DeletePlaylistErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vDeletePlaylistData, data),
    responseValidator: async (data) => await v.parseAsync(vDeletePlaylistResponse, data),
    url: '/api/playlist/{uuid}',
    ...options
});

export const updatePlaylist = <ThrowOnError extends boolean = false>(options: Options<UpdatePlaylistData, ThrowOnError>) => (options.client ?? client).put<UpdatePlaylistResponses, UpdatePlaylistErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vUpdatePlaylistData, data),
    responseValidator: async (data) => await v.parseAsync(vUpdatePlaylistResponse, data),
    url: '/api/playlist/{uuid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const readSchedule = <ThrowOnError extends boolean = false>(options?: Options<ReadScheduleData, ThrowOnError>) => (options?.client ?? client).get<ReadScheduleResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vReadScheduleData, data),
    responseValidator: async (data) => await v.parseAsync(vReadScheduleResponse, data),
    url: '/api/schedule',
    ...options
});

export const createSchedule = <ThrowOnError extends boolean = false>(options: Options<CreateScheduleData, ThrowOnError>) => (options.client ?? client).post<CreateScheduleResponses, CreateScheduleErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vCreateScheduleData, data),
    responseValidator: async (data) => await v.parseAsync(vCreateScheduleResponse, data),
    url: '/api/schedule',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteSchedule = <ThrowOnError extends boolean = false>(options: Options<DeleteScheduleData, ThrowOnError>) => (options.client ?? client).delete<DeleteScheduleResponses, DeleteScheduleErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vDeleteScheduleData, data),
    responseValidator: async (data) => await v.parseAsync(vDeleteScheduleResponse, data),
    url: '/api/schedule/{uuid}',
    ...options
});

export const scheduleInfo = <ThrowOnError extends boolean = false>(options: Options<ScheduleInfoData, ThrowOnError>) => (options.client ?? client).get<ScheduleInfoResponses, ScheduleInfoErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vScheduleInfoData, data),
    responseValidator: async (data) => await v.parseAsync(vScheduleInfoResponse, data),
    url: '/api/schedule/{uuid}',
    ...options
});

export const updateSchedule = <ThrowOnError extends boolean = false>(options: Options<UpdateScheduleData, ThrowOnError>) => (options.client ?? client).put<UpdateScheduleResponses, UpdateScheduleErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vUpdateScheduleData, data),
    responseValidator: async (data) => await v.parseAsync(vUpdateScheduleResponse, data),
    url: '/api/schedule/{uuid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
