// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8562' | (string & {});
};

export type DeleteFilesRequest = {
    /**
     * path of files /dirs to be deleted.
     *
     * May not handle case where a folder and a file inside the folder is to be deleted in the same request
     */
    ids: Array<string>;
};

export type Display = {
    display_material: DisplayMaterial;
    name: string;
    uuid: string;
};

export type DisplayMaterial = {
    type: 'schedule';
    uuid: string;
} | {
    type: 'playlist';
    uuid: string;
};

/**
 * Struct representing the multipart/form-data schema for file uploads
 */
export type FileUpload = {
    /**
     * Target directory to upload files to
     */
    directory: string;
    /**
     * One or more files to upload
     */
    files: Array<Blob | File>;
};

export type ImageData = {
    duration: number;
    src: string;
};

export type ListView = Array<ListViewItem>;

export type ListViewItem = {
    date: string;
    id: string;
    size: number;
    type: ListViewItemType;
};

export type ListViewItemType = 'folder' | 'file';

export type NextMoment = {
    /**
     * Amount of milliseconds until change
     */
    in_ms: number;
    playlist: string;
};

export type Payload = {
    content: Array<Display>;
    type: 'Display';
} | {
    content: Array<Playlist>;
    type: 'Playlist';
} | {
    content: Array<Schedule>;
    type: 'Schedule';
} | {
    content: {
        code: number;
        message: string;
    };
    type: 'Error';
};

export type Playlist = {
    items: Array<PlaylistItem>;
    name: string;
    uuid: string;
};

export type PlaylistItem = {
    id: string;
    settings: WebsiteData;
    type: 'WEBSITE';
} | {
    id: string;
    settings: TextData;
    type: 'TEXT';
} | {
    id: string;
    settings: ImageData;
    type: 'IMAGE';
} | {
    id: string;
    settings: ImageData;
    type: 'BACKGROUND_AUDIO';
};

export type Schedule = {
    name: string;
    playlist: string;
    scheduled?: Array<ScheduledPlaylistInput> | null;
    uuid: string;
};

export type ScheduleInfo = {
    current: string;
    next?: null | NextMoment;
};

export type ScheduledPlaylistInput = {
    end: string;
    playlist: string;
    start: string;
};

export type TextData = {
    duration: number;
    text: string;
};

export type TreeDirectory = {
    directories: Array<TreeDirectory>;
    files: Array<TreeFile>;
    id: string;
    name: string;
};

export type TreeFile = {
    date: string;
    id: string;
    name: string;
    size: number;
};

export type WebsiteData = {
    duration: number;
    url: string;
};

export type ReadDisplaysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/display';
};

export type ReadDisplaysResponses = {
    /**
     * Get all Displays
     */
    200: Array<{
        display_material: DisplayMaterial;
        name: string;
        uuid: string;
    }>;
};

export type ReadDisplaysResponse = ReadDisplaysResponses[keyof ReadDisplaysResponses];

export type CreateDisplayData = {
    body: Display;
    path?: never;
    query?: never;
    url: '/api/display';
};

export type CreateDisplayErrors = {
    /**
     * Bad Request (e.g., name taken)
     */
    400: Payload;
    /**
     * Server Error
     */
    500: Payload;
};

export type CreateDisplayError = CreateDisplayErrors[keyof CreateDisplayErrors];

export type CreateDisplayResponses = {
    /**
     * Display created
     */
    200: Payload;
};

export type CreateDisplayResponse = CreateDisplayResponses[keyof CreateDisplayResponses];

export type DeleteDisplayData = {
    body?: never;
    path: {
        /**
         * Uuid of Display to delete
         */
        uuid: string;
    };
    query?: never;
    url: '/api/display/{uuid}';
};

export type DeleteDisplayErrors = {
    /**
     * No Display exists with given Uuid
     */
    400: Payload;
};

export type DeleteDisplayError = DeleteDisplayErrors[keyof DeleteDisplayErrors];

export type DeleteDisplayResponses = {
    /**
     * Display deleted
     */
    200: Payload;
};

export type DeleteDisplayResponse = DeleteDisplayResponses[keyof DeleteDisplayResponses];

export type UpdateDisplayData = {
    body: Display;
    path: {
        /**
         * Uuid of Display to delete
         */
        uuid: string;
    };
    query?: never;
    url: '/api/display/{uuid}';
};

export type UpdateDisplayErrors = {
    400: Payload;
};

export type UpdateDisplayError = UpdateDisplayErrors[keyof UpdateDisplayErrors];

export type UpdateDisplayResponses = {
    /**
     * Display updated
     */
    200: {
        content: Array<Display>;
        type: 'Display';
    } | {
        content: Array<Playlist>;
        type: 'Playlist';
    } | {
        content: Array<Schedule>;
        type: 'Schedule';
    } | {
        content: {
            code: number;
            message: string;
        };
        type: 'Error';
    };
};

export type UpdateDisplayResponse = UpdateDisplayResponses[keyof UpdateDisplayResponses];

export type DeleteFilesData = {
    body: DeleteFilesRequest;
    path?: never;
    query?: never;
    url: '/api/files';
};

export type DeleteFilesErrors = {
    /**
     * Bad Request
     */
    400: Payload;
};

export type DeleteFilesError = DeleteFilesErrors[keyof DeleteFilesErrors];

export type DeleteFilesResponses = {
    /**
     * Files deleted successfully
     */
    200: Payload;
};

export type DeleteFilesResponse = DeleteFilesResponses[keyof DeleteFilesResponses];

export type AddFilesData = {
    body: FileUpload;
    path?: never;
    query?: never;
    url: '/api/files';
};

export type AddFilesErrors = {
    /**
     * Bad Request (e.g. missing directory field)
     */
    400: Payload;
};

export type AddFilesError = AddFilesErrors[keyof AddFilesErrors];

export type AddFilesResponses = {
    /**
     * Files uploaded successfully
     */
    200: Payload;
};

export type AddFilesResponse = AddFilesResponses[keyof AddFilesResponses];

export type GetAllPathsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/files/list';
};

export type GetAllPathsListResponses = {
    /**
     * List all files flat
     */
    200: Payload;
};

export type GetAllPathsListResponse = GetAllPathsListResponses[keyof GetAllPathsListResponses];

export type GetAllPathsTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/files/tree';
};

export type GetAllPathsTreeResponses = {
    /**
     * Get file tree
     */
    200: TreeDirectory;
};

export type GetAllPathsTreeResponse = GetAllPathsTreeResponses[keyof GetAllPathsTreeResponses];

export type ReadPlaylistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/playlist';
};

export type ReadPlaylistResponses = {
    /**
     * Get all Playlists
     */
    200: Array<{
        items: Array<PlaylistItem>;
        name: string;
        uuid: string;
    }>;
};

export type ReadPlaylistResponse = ReadPlaylistResponses[keyof ReadPlaylistResponses];

export type CreatePlaylistData = {
    body: Playlist;
    path?: never;
    query?: never;
    url: '/api/playlist';
};

export type CreatePlaylistErrors = {
    /**
     * Bad Request
     */
    400: Payload;
    /**
     * Server Error
     */
    500: Payload;
};

export type CreatePlaylistError = CreatePlaylistErrors[keyof CreatePlaylistErrors];

export type CreatePlaylistResponses = {
    /**
     * Playlist created
     */
    200: Payload;
};

export type CreatePlaylistResponse = CreatePlaylistResponses[keyof CreatePlaylistResponses];

export type DeletePlaylistData = {
    body?: never;
    path: {
        /**
         * Uuid of Playlist to delete
         */
        uuid: string;
    };
    query?: never;
    url: '/api/playlist/{uuid}';
};

export type DeletePlaylistErrors = {
    400: Payload;
};

export type DeletePlaylistError = DeletePlaylistErrors[keyof DeletePlaylistErrors];

export type DeletePlaylistResponses = {
    /**
     * Playlist deleted
     */
    200: Payload;
};

export type DeletePlaylistResponse = DeletePlaylistResponses[keyof DeletePlaylistResponses];

export type UpdatePlaylistData = {
    body: Playlist;
    path: {
        /**
         * Uuid of Playlist to update
         */
        uuid: string;
    };
    query?: never;
    url: '/api/playlist/{uuid}';
};

export type UpdatePlaylistErrors = {
    /**
     * Bad Request
     */
    400: Payload;
    /**
     * Server Error
     */
    500: Payload;
};

export type UpdatePlaylistError = UpdatePlaylistErrors[keyof UpdatePlaylistErrors];

export type UpdatePlaylistResponses = {
    /**
     * Playlist updated
     */
    200: Payload;
};

export type UpdatePlaylistResponse = UpdatePlaylistResponses[keyof UpdatePlaylistResponses];

export type ReadScheduleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/schedule';
};

export type ReadScheduleResponses = {
    /**
     * Get all Schedules
     */
    200: Array<{
        name: string;
        playlist: string;
        scheduled?: Array<ScheduledPlaylistInput> | null;
        uuid: string;
    }>;
};

export type ReadScheduleResponse = ReadScheduleResponses[keyof ReadScheduleResponses];

export type CreateScheduleData = {
    body: Schedule;
    path?: never;
    query?: never;
    url: '/api/schedule';
};

export type CreateScheduleErrors = {
    /**
     * Bad Request
     */
    400: Payload;
    /**
     * Server Error
     */
    500: Payload;
};

export type CreateScheduleError = CreateScheduleErrors[keyof CreateScheduleErrors];

export type CreateScheduleResponses = {
    /**
     * Schedule created
     */
    200: Payload;
};

export type CreateScheduleResponse = CreateScheduleResponses[keyof CreateScheduleResponses];

export type DeleteScheduleData = {
    body?: never;
    path: {
        /**
         * Uuid of Schedule to delete
         */
        uuid: string;
    };
    query?: never;
    url: '/api/schedule/{uuid}';
};

export type DeleteScheduleErrors = {
    400: Payload;
};

export type DeleteScheduleError = DeleteScheduleErrors[keyof DeleteScheduleErrors];

export type DeleteScheduleResponses = {
    /**
     * Schedule deleted
     */
    200: Payload;
};

export type DeleteScheduleResponse = DeleteScheduleResponses[keyof DeleteScheduleResponses];

export type ScheduleInfoData = {
    body?: never;
    path: {
        /**
         * Uuid of Schedule to fetch info for
         */
        uuid: string;
    };
    query?: never;
    url: '/api/schedule/{uuid}';
};

export type ScheduleInfoErrors = {
    /**
     * Schedule not found
     */
    404: unknown;
};

export type ScheduleInfoResponses = {
    /**
     * Schedule information
     */
    200: ScheduleInfo;
};

export type ScheduleInfoResponse = ScheduleInfoResponses[keyof ScheduleInfoResponses];

export type UpdateScheduleData = {
    body: Schedule;
    path: {
        /**
         * Uuid of Schedule to update
         */
        uuid: string;
    };
    query?: never;
    url: '/api/schedule/{uuid}';
};

export type UpdateScheduleErrors = {
    /**
     * Bad Request
     */
    400: Payload;
    /**
     * Server Error
     */
    500: Payload;
};

export type UpdateScheduleError = UpdateScheduleErrors[keyof UpdateScheduleErrors];

export type UpdateScheduleResponses = {
    /**
     * Schedule updated
     */
    200: Payload;
};

export type UpdateScheduleResponse = UpdateScheduleResponses[keyof UpdateScheduleResponses];
