// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vDeleteFilesRequest = v.object({
    ids: v.array(v.string())
});

export const vDisplayMaterial = v.union([v.object({
        type: v.picklist(['schedule']),
        uuid: v.pipe(v.string(), v.uuid())
    }), v.object({
        type: v.picklist(['playlist']),
        uuid: v.pipe(v.string(), v.uuid())
    })]);

export const vDisplay = v.object({
    display_material: vDisplayMaterial,
    name: v.string(),
    uuid: v.pipe(v.string(), v.uuid())
});

/**
 * Struct representing the multipart/form-data schema for file uploads
 */
export const vFileUpload = v.object({
    directory: v.string(),
    files: v.array(v.string())
});

export const vImageData = v.object({
    duration: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    src: v.string()
});

export const vListViewItemType = v.picklist(['folder', 'file']);

export const vListViewItem = v.object({
    date: v.string(),
    id: v.string(),
    size: v.pipe(v.number(), v.integer(), v.minValue(0)),
    type: vListViewItemType
});

export const vListView = v.array(vListViewItem);

export const vNextMoment = v.object({
    in_ms: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    playlist: v.pipe(v.string(), v.uuid())
});

export const vScheduleInfo = v.object({
    current: v.pipe(v.string(), v.uuid()),
    next: v.optional(v.union([v.null(), vNextMoment]))
});

export const vScheduledPlaylistInput = v.object({
    end: v.string(),
    playlist: v.pipe(v.string(), v.uuid()),
    start: v.string()
});

export const vSchedule = v.object({
    name: v.string(),
    playlist: v.pipe(v.string(), v.uuid()),
    scheduled: v.optional(v.union([v.array(vScheduledPlaylistInput), v.null()])),
    uuid: v.pipe(v.string(), v.uuid())
});

export const vTextData = v.object({
    duration: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    text: v.string()
});

export const vTreeFile = v.object({
    date: v.string(),
    id: v.string(),
    name: v.string(),
    size: v.pipe(v.number(), v.integer(), v.minValue(0))
});

export const vTreeDirectory: v.GenericSchema = v.object({
    directories: v.array(v.lazy(() => vTreeDirectory)),
    files: v.array(vTreeFile),
    id: v.string(),
    name: v.string()
});

export const vWebsiteData = v.object({
    duration: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    url: v.string()
});

export const vPlaylistItem = v.union([
    v.object({
        id: v.string(),
        settings: vWebsiteData,
        type: v.picklist(['WEBSITE'])
    }),
    v.object({
        id: v.string(),
        settings: vTextData,
        type: v.picklist(['TEXT'])
    }),
    v.object({
        id: v.string(),
        settings: vImageData,
        type: v.picklist(['IMAGE'])
    }),
    v.object({
        id: v.string(),
        settings: vImageData,
        type: v.picklist(['BACKGROUND_AUDIO'])
    })
]);

export const vPlaylist = v.object({
    items: v.array(vPlaylistItem),
    name: v.string(),
    uuid: v.pipe(v.string(), v.uuid())
});

export const vPayload = v.union([
    v.object({
        content: v.array(vDisplay),
        type: v.picklist(['Display'])
    }),
    v.object({
        content: v.array(vPlaylist),
        type: v.picklist(['Playlist'])
    }),
    v.object({
        content: v.array(vSchedule),
        type: v.picklist(['Schedule'])
    }),
    v.object({
        content: v.object({
            code: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
            message: v.string()
        }),
        type: v.picklist(['Error'])
    })
]);

export const vReadDisplaysData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Get all Displays
 */
export const vReadDisplaysResponse = v.array(v.object({
    display_material: vDisplayMaterial,
    name: v.string(),
    uuid: v.pipe(v.string(), v.uuid())
}));

export const vCreateDisplayData = v.object({
    body: vDisplay,
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Display created
 */
export const vCreateDisplayResponse = vPayload;

export const vDeleteDisplayData = v.object({
    body: v.optional(v.never()),
    path: v.object({
        uuid: v.pipe(v.string(), v.uuid())
    }),
    query: v.optional(v.never())
});

/**
 * Display deleted
 */
export const vDeleteDisplayResponse = vPayload;

export const vUpdateDisplayData = v.object({
    body: vDisplay,
    path: v.object({
        uuid: v.pipe(v.string(), v.uuid())
    }),
    query: v.optional(v.never())
});

/**
 * Display updated
 */
export const vUpdateDisplayResponse = v.union([
    v.object({
        content: v.array(vDisplay),
        type: v.picklist(['Display'])
    }),
    v.object({
        content: v.array(vPlaylist),
        type: v.picklist(['Playlist'])
    }),
    v.object({
        content: v.array(vSchedule),
        type: v.picklist(['Schedule'])
    }),
    v.object({
        content: v.object({
            code: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
            message: v.string()
        }),
        type: v.picklist(['Error'])
    })
]);

export const vDeleteFilesData = v.object({
    body: vDeleteFilesRequest,
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Files deleted successfully
 */
export const vDeleteFilesResponse = vPayload;

export const vAddFilesData = v.object({
    body: vFileUpload,
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Files uploaded successfully
 */
export const vAddFilesResponse = vPayload;

export const vGetAllPathsListData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * List all files flat
 */
export const vGetAllPathsListResponse = vPayload;

export const vGetAllPathsTreeData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Get file tree
 */
export const vGetAllPathsTreeResponse = vTreeDirectory;

export const vReadPlaylistData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Get all Playlists
 */
export const vReadPlaylistResponse = v.array(v.object({
    items: v.array(vPlaylistItem),
    name: v.string(),
    uuid: v.pipe(v.string(), v.uuid())
}));

export const vCreatePlaylistData = v.object({
    body: vPlaylist,
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Playlist created
 */
export const vCreatePlaylistResponse = vPayload;

export const vDeletePlaylistData = v.object({
    body: v.optional(v.never()),
    path: v.object({
        uuid: v.pipe(v.string(), v.uuid())
    }),
    query: v.optional(v.never())
});

/**
 * Playlist deleted
 */
export const vDeletePlaylistResponse = vPayload;

export const vUpdatePlaylistData = v.object({
    body: vPlaylist,
    path: v.object({
        uuid: v.pipe(v.string(), v.uuid())
    }),
    query: v.optional(v.never())
});

/**
 * Playlist updated
 */
export const vUpdatePlaylistResponse = vPayload;

export const vReadScheduleData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Get all Schedules
 */
export const vReadScheduleResponse = v.array(v.object({
    name: v.string(),
    playlist: v.pipe(v.string(), v.uuid()),
    scheduled: v.optional(v.union([v.array(vScheduledPlaylistInput), v.null()])),
    uuid: v.pipe(v.string(), v.uuid())
}));

export const vCreateScheduleData = v.object({
    body: vSchedule,
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * Schedule created
 */
export const vCreateScheduleResponse = vPayload;

export const vDeleteScheduleData = v.object({
    body: v.optional(v.never()),
    path: v.object({
        uuid: v.pipe(v.string(), v.uuid())
    }),
    query: v.optional(v.never())
});

/**
 * Schedule deleted
 */
export const vDeleteScheduleResponse = vPayload;

export const vScheduleInfoData = v.object({
    body: v.optional(v.never()),
    path: v.object({
        uuid: v.pipe(v.string(), v.uuid())
    }),
    query: v.optional(v.never())
});

/**
 * Schedule information
 */
export const vScheduleInfoResponse = vScheduleInfo;

export const vUpdateScheduleData = v.object({
    body: vSchedule,
    path: v.object({
        uuid: v.pipe(v.string(), v.uuid())
    }),
    query: v.optional(v.never())
});

/**
 * Schedule updated
 */
export const vUpdateScheduleResponse = vPayload;
