// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayMaterial } from "../create/DisplayMaterial";

export type UpdateDisplay = { name: string, display_material: DisplayMaterial, };
