// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduledPlaylistInput } from "./ScheduledPlaylistInput";

export interface UpdateSchedule { name: string, playlist: string, scheduled?: Array<ScheduledPlaylistInput>, }