// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeleteFilesRequest = { 
/**
 * path of files /dirs to be deleted.
 *
 * May not handle case where a folder and a file inside the folder is to be deleted in the same request
 */
ids: Array<string>, };
