// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListViewItemType } from "./ListViewItemType";

export type ListViewItem = { id: string, size: number, date: string, type: ListViewItemType, };
