// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TreeView = { content: string, 
/**
 * children is Some if content is a dir, None if content is a file
 */
children: Array<TreeView> | null, };
