// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeFile } from "./TreeFile";

export type TreeDirectory = { id: string, name: string, files: Array<TreeFile>, directories: Array<TreeDirectory>, };
