// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplayMaterial = { "type": "schedule", "uuid": string } | { "type": "playlist", "uuid": string };
