// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NextMoment = { 
/**
 * Amount of milliseconds until change
 */
in_ms: bigint, playlist: string, };
