// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextMoment } from "./NextMoment";

export type ScheduleInfo = { current: string, next: NextMoment | null, };
